apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteXJlZ2lzdHJ5LmNvbSI6eyJ1c2VybmFtZSI6InJvb3QiLCJwYXNzd29yZCI6IlBAc3N3MHJkIiwiYXV0aCI6ImNtOXZkRHBRUUhOemR6QnlaQT09In19fQ==
